debug: true

logging:
  level:
    ROOT: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    com.looseboxes.mailsender: DEBUG

spring:
  profiles:
    active: dev
    include:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
#      additional-exclude: .h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  mail:
    debug: true
    host: smtp.gmail.com
    port: 587
    username: ${webstore.user.system.name}
    password: 
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

  datasource: 
    platform: h2
    url: jdbc:h2:file:./target/loosebox_db2;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
