debug: false

logging:
  level:
    ROOT: INFO
#    com.looseboxes.webform.controllers.FormControllerBase: TRACE
#    com.looseboxes.webform.services.FormService: TRACE
    io.github.jhipster: INFO
    com.looseboxes.mailsender: INFO
    com.looseboxes.webform: INFO
    
spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mailsender.user.system.name}
    password: 
  thymeleaf:
    cache: true
    
  datasource: 
    initialization-mode: always
    platform: mysql
#    url: jdbc:h2:file:./.mailsender/h2db/db/loosebox_db2;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    url: jdbc:mysql://uranus.ignitionserver.net:3306/loosebox_db2?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: loosebox_root
    password: 
  jpa: 
    generate-ddl: false
    open-in-view: false
    show-sql: false
    hibernate:
     ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
